fixtures:
  repositories:
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    yum: "https://github.com/voxpupuli/puppet-yum"
  symlinks:
    "veeamagent": "#{source_dir}"
