language: ruby
cache: bundler
matrix:
  include:
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.0"
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 5.0"
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes"
script: bundle exec rake tests
notifications:
  email:
    on_failure: change
    on_success: never
  slack:
    rooms:
      - secure: Ih2UcIgsfcc66Ko61R6NizyN8fk4JaXWG6Wffd0wtd1lL60bdy4wDA54QEBEJhPF3/RZPrLiCIiAkaV0uaG1b5KGonEXSSVWqqSqTwmXmrrGTKjkRCS4EIC2etTFibOYaFuhqysvKIDuKdKkHEMINtdx1oohuD1WZrV+zaJJ0+zEMg6OE5qFvafiqTa0bHN+Lpb6rsUkzpkJ7dwUYg7DGBaSp5BNHEqOINmjy/CYbN+Uuq7XMk+cVjD5KsxJGiM05ATeIVvIu6Hc3DMQWQ9z72pHJNBZOy2qwZoTE9o+gCbWzb7FpDazehB9namZVLqLAsnid1Ks4UEEikZta+2IkIa1qW2Bqli5nd3ix9JmrvKtsTLSYTxU/278Jg9JXI5HsdqUsu42ihXBfkTeTbIAQdLLozvkX1gp41uPU+fZuqQKJ1zml9wxXMAdeHGXBegvQ/EP2HN8S9HKZGbUQaTaaM6d8Z/JoM3gS+zyGjmk166gQohrv4+Mt1NZIljGmWXy4xEP3MbTLoLztPXDz4m/eE6wIU+gBcNuJYqdhZCLUDTWFLpk+rLu/jR0WDs89TSlSwW/xtNP8LfCC6Zi7KK4TUvKoMFTApjI0ygo7AfqvLFPMoKBmeA+2XcNlb/FCC18lBdmCF9Ny4Qq1YTnd4tl/GW4LX1foXNLDzwmLkspIFo=
      - secure: rRYuuwIOe7eDYTjgykco7CcI0qTZa6H2Eg/xH+OoDP5TAHKgqO1Uclw5hLyRG+foTjCpG3FyQj/TEwG6u8ihY89PNL7mA/vXZMuj4wLk9alktOzfRKFNqb2s82bJYT5xN5aiMUKF/e5Ciohc2kL34evl92B47v6G5rhu6ZmjtvNbET2bVG3s0wVpMfDAhnYNnlbfJ1HLFOIiPmi0dCiNTYWSnUg4i3B43lMO1bfgaetF0mm+X928dNNdPoGIatJGsGx0DNEFxKusFVvr1KUaxnEr6Pqio+aYKJesFp98Ltcl39ejy1LOxJXUyb9uARJjjt31Jh1bplWnLHGQb6F9xRHdhMC4rcMzrA+zxqT4JOr/p2YILley0Kw3qNcHhcjgS1NZ3XN+ltR+8dn1B0IhZwra3jJsT8iVQN3jlm9X8tbn5NGTK67iMBrulkm7gTxcBXXs6rLIscqm/G5tFcrPRX6hvkgyjkFabH1vHwIVLlnjBSochlkmIP+zxH4pfKc1wZQsoTWLEPv8NGOilPoSbR9XZuxMKu/woiJi7NkHWWRzcvyD0rBjPpEew3PvvMNXOUPUzBND4h6E8stdQYZsB1aHE7Npajkzltkd8JYZ1C2oV+UnNgjGqFlvMPuV7AV8Kz+3vCLD6AV+zHHA+AVILRDrvGLl9YbWWE7wArcl+b4=
